export default {
	spinitsso: (p, cburl)=> `/${p.lang}/spinitsso-redirect?callbackURL=${cburl}`,
	logout: (p, cburl)=> `/${p.lang}/logout?returnURL=${cburl}`,
	base: p => `/${p.lang}`,
	resetPSW: p => `/${p.lang}/u=${p.user}&t=${p.token}&a=resetpwd&lang=${p.lang}`,
	contactus: p => `/${p.lang}/contactus`,
	demoLogin: p => `/${p.lang}/u=${p.user}&t=${p.token}&a=demologin&lang=${p.lang}`,
	initChangePSW: p => `/${p.lang}/u=${p.user}&t=${p.token}&a=initpwd&lang=${p.lang}`,
	login: p => `/${p.lang}/login`,
	config: p => `/${p.lang}/platform/config`,
	workday: p => `/${p.lang}/service/${p.cusnum}/workday`,
	main: p => `/${p.lang}/${p.customerId||''}`,
	kpi: p => `/${p.lang}/${p.customerId}/kpi`,
	Actuality: p => `/${p.lang}/${p.customerId}/actuality`,
	KPIActuality: p => `/${p.lang}/${p.customerId}/actuality`,
	KPIGroupConfig: p => `/${p.lang}/${p.customerId}/actuality/config`,
	KPIConfig: p => `/${p.lang}/${p.customerId}/actuality/config/kpiconfig`,
	KPIRankConfig: p => `/${p.lang}/${p.customerId}/actuality/config/rankconfig`,
	KPITemplate:p => `/${p.lang}/${p.customerId}/actuality/template`,
	dataAnalysis:p => `/${p.lang}/${p.customerId}/data_analysis`,
	inputData:p => `/${p.lang}/${p.customerId}/input_data`,
	ecm:p => `/${p.lang}/${p.customerId}/energy_conservation_measures`,
	smartDiagnose:p=>`/${p.lang}/${p.customerId}/smartDiagnose`,
	setting: p => `/${p.lang}/${p.customerId}/setting`,
	alarm: p => `/${p.lang}/${p.customerId}/alarm`,
	map: p => `/${p.lang}/${p.customerId}/map`,
	report:{
		actualityKpi: p => `/${p.lang}/${p.customerId}/actuality/kpi`,
		actualityReport: p => `/${p.lang}/${p.customerId}/actuality/report`,
		actualityBuildingReport: p => `/${p.lang}/${p.customerId}/actuality/building_report`,
		dailyReport: p => `/${p.lang}/${p.customerId}/dailyReport`,
		template: p => `/${p.lang}/${p.customerId}/template`,
	},
	saveEffect: {
		index: p => `/${p.lang}/${p.customerId}/save_effect`,
		overview: p => `/${p.lang}/${p.customerId}/save_effect/overview`,
		list: p => `/${p.lang}/${p.customerId}/save_effect/effect/list`,
		listBase: p => `/${p.lang}/${p.customerId}/save_effect/effect`,
		bestBase: p => `/${p.lang}/${p.customerId}/save_effect/best`,
		best: p => `/${p.lang}/${p.customerId}/save_effect/best/list`,
		ignoredbBest: p => `/${p.lang}/${p.customerId}/save_effect/best/ignored`,
		detail: p => `/${p.lang}/${p.customerId}/save_effect/detail`,
		drafts: p => `/${p.lang}/${p.customerId}/save_effect/effect/drafts`,
	},
	customerSetting:{
		ptag:p => `/${p.lang}/${p.customerId}/ptag`,
		vtag:p => `/${p.lang}/${p.customerId}/vtag`,
		vee:p => `/${p.lang}/${p.customerId}/vee`,
		log:p => `/${p.lang}/${p.customerId}/log`,
		hierNode:p => `/${p.lang}/${p.customerId}/hierNode`,
		hierLog:p => `/${p.lang}/${p.customerId}/hierLog`,
		customerLabeling:p => `/${p.lang}/${p.customerId}/customerLabeling`,
		KPICycle:p => `/${p.lang}/${p.customerId}/KPICycle`,
	},
	service: {
		workday: p => `/${p.lang}/service/${p.cusnum}/workday`,
		worktime: p => `/${p.lang}/service/${p.cusnum}/worktime`,
		coldwarm: p => `/${p.lang}/service/${p.cusnum}/coldwarm`,
		daynight: p => `/${p.lang}/service/${p.cusnum}/daynight`,
		price: p => `/${p.lang}/service/${p.cusnum}/price`,
		carbon: p => `/${p.lang}/service/${p.cusnum}/carbon`,
		benchmark: p => `/${p.lang}/service/${p.cusnum}/benchmark`,
		labeling: p => `/${p.lang}/service/${p.cusnum}/labeling`,
		customer: p => `/${p.lang}/service/${p.cusnum}/customer`,
		user: p => `/${p.lang}/service/${p.cusnum}/user`,
		privilege: p => `/${p.lang}/service/${p.cusnum}/privilege`,
	},
	// platform: {
		config: p => `/${p.lang}/platform/config`,
		mail: p => `/${p.lang}/platform/mail`,
	// }
	blankPage: p => `/${p.lang}/${p.customerId}/blankPage`,
}
