'use strict';

module.exports = {
  Hierarchy: {
    GetBuildingList: '/Hierarchy/GetBuildingList/{customerId}',
    getConsultants: '/user/getconsultants/{hierarchyId}',
  },
  RawData:{
    RollBack:'/energy/rollback/{tagId}'
  },
  KPI:{
		getKPIPeriod: '/kpi/getkpiperiod/{customerid}',
		setKPIPeriod: '/kpi/setkpiperiod',
		getKPIPeriodByYear: '/kpi/getkpiperiodpoint/{customerid}/{year}',
		getDimension:'/AreaDimension/GetAreaDimensionTree',
		getTags:'/Tag/GetTagsByFilter',
    getKPIConfigured: '/kpi/{HierarchyId}/{groupKpiId}/validyears',
    getKPIChart: '/KPI/chart/{groupKpiId}/{year}/{HierarchyId}',
    getKPIChartSummary: '/KPI/calcpredictsum/{customerId}/{year}/{HierarchyId}/{groupKpiId}',
    getKpi:'/kpi/settings/{kpiId}/{year}',
    getCalcValue:'/kpi/calckpigradualvalue',
    IsAutoCalculable:'/kpi/isautocalculable/{customerId}/{tagId}/{year}',
    // getCalcPredicate:'/kpi/CalcKPIPredicateValue',
    getCalcPredicate:'/kpi/predictionCalculation',
    createKpiReportSettings:'/kpi/settings/create',
    updateKpiReportSettings:'/kpi/settings/update',
    updatePredictionSetting:'/kpi/PredictionSetting/update',
    customerCurrentYear:'/kpi/customercurrentyear/{customerId}',
    updateMobileViewState: '/kpi/updatemobileviewstate/{kpiId}/{state}',
    Group:{
      groupSettingsList: '/kpi/groupsettings/list/{customerId}',
      groupcontinuous:'/kpi/groupcontinuous/{KpiId}/{year}',
      getGroupByYear:'/kpi/availablegroup/{customerId}/{year}',
      getGroupSetting:'/kpi/groupsettings/{kpiSettingsId}',
      create:'/kpi/groupsettings/create',
      update:'/kpi/groupsettings/update',
      delete:'/kpi/groupsettings/delete/{kpiSettingsId}',
      getGroupKpis:'/kpi/getgroupkpis/{customerId}',
      calckpigradualsumvalue:'/kpi/calckpigradualsumvalue',
      totalIndicator:'/kpi/SavingRateType/TotalIndicator/{customerId}/{year}'
    },
    Rank: {
      getBuildingRank: '/rank/buildingrank/{customerId}/{buildingId}/{year}',
      getGroupKPIBuildingRank: '/rank/groupkpibuildingrank/{customerId}/{groupKpiId}/{buildingId}/{year}',
      getGroupRank: '/rank/grouprank/{customerId}/{year}',
      getRank:'/rank/getrank/{customerId}',
      setRank:'/rank/setrank',
      rankRecord:'/rank/rankrecord/{customerId}/{groupKpiId}/{rankType}/{buildingId}/{year}',
      setMobileViewState: '/rank/setmobileviewstate/{rankType}/{kpiId}/{state}',
    }
	},
  DataReport: {
    getExportByHierarchyId: '/DataReport/GetExportByHierarchyId',
    templateReference:'/datareport/TemplateReference/{templateName}/{customerId}',
    templateReplace:'/datareport/TemplateReplace/{originName}/{replaceName}/{customerId}'
  },
  DataAnalysis:{
    getWidgetGatherInfo:'/Widget/GetWidgetGatherInfo',
    getProwidgetgatherinfo:'/widget/prowidgetgatherinfo',
    getLatestRawData:'/energy/Tag/{tagId}/LatestRawData',
    getCityWeatherTag:'/Dashboard/cityWeatherTag/{cityId}',
    getWidgetsplitgatherinfo:'/widget/widgetsplitgatherinfo',
    getTouTariffSplitGatherInfo:'/widget/TouTariffSplitGatherInfo',
    getScatterPlotData:'/energy/scatterPlotData',
    getBubbleData:'/energy/bubbleData'
  },
  ECM:{
    getEnergysolution:'/energysolution/{hierarchyId}/{status}/{smallSize}/{size}',
    pushProblem:'/energysolution/problem/push',
    deleteProblem:'/energysolution/problem/delete/{problemId}',
    updateSolution:'/energysolution/update',
    getSupervisor:'/energysolution/supervisor/{hierarchyId}/{energySys}',
    saveSupervisor:'/energysolution/supervisor',
    assignSupervisor:'/energysolution/problem/supervisor/assignation/{problemId}/{supervisorId}',
    activecounts:'/energysolution/problem/activecounts/{hierarchyId}',
    containsunread:'/energysolution/problem/containsunread/{hierarchyId}',
    readProblem:'/energysolution/problem/read/{problemId}',
    remarkList:'/energysolution/problem/remark/{problemId}',
    addRemark:'/energysolution/problem/remark',
    deleteRemark:'/energysolution/problem/remark/delete/{remarkId}',
    deleteSupervisor:'/energysolution/problem/supervisor/delete/{supervisorId}',
  },
  Diagnose:{
    diagnosislist:'/diagnose/diagnosislist',
    getdiagnosestatic:'/diagnose/getdiagnosestatic/{hierarchId}',
    getDiagnose:'/diagnose/get/{diagnoseId}',
    deletediagnose:'/diagnose/deletediagnose/{diagnoseId}',
    getdiagnosedata:'/diagnose/getdiagnosedata/{diagnoseId}',
    getproblemdata:'/diagnose/getproblemdata/{diagnoseId}',
    pauseorrecoverdiagnose:'/diagnose/pauseorrecoverdiagnose/{diagnoseId}/{status}',
    ignorediagnose:'/diagnose/ignorediagnose/{diagnoseId}',
    previewchart:'/diagnose/previewchart',
    getDiagnoseTag: '/diagnose/getdiagnosetag',
    getDiagnoseAssociateTag: '/diagnose/getassociatetag',
    updateDiagnose:'/diagnose/update',
    generatesolution:'/diagnose/generatesolution/{diagnoseId}',
    isconfigcalendar:'/diagnose/isconfigcalendar/{dueDate}/{hierarchyId}',
    getConsultant: '/user/getconsultant/{hierarchyId}',
    energySolution:'/diagnose/{diagnoseId}/energysolution/create',
    getSuggestSolutions: '/energysolution/solutions',
    createSolution: '/energysolution/create',
    checkTitle: '/energysolution/checkTitle',
  },

  SaveEffect: {
    getEnergyEffectTags: '/energyeffect/getenergyeffecttags/{energyProblemId}/{state}',
    energyEffectPriview: '/energyeffect/priview',
    getEnergySolution: '/energysolution/{problemid}/{smallsize}/{size}',
    addItem: '/energyeffect/additem/{customerId}/{hierarchyId}/{energySystem}',
    getenergyeffect:'/energyeffect/getenergyeffect/{hierarchyId}',
    getenergyeffectratetags:'/energyeffect/getenergyeffectratetags/{hierarchyId}',
    saveenergyeffectratetags:'/energyeffect/saveeffectratetag/{customerId}/{hierarchyId}',
    getDetail:'/energyeffect/detail/{energyEffectId}',
    deleteitem:'/energyeffect/deleteitem/{energyEffectItemId}',
    getitemlist:'/energyeffect/getitemlist/{hierarchyId}/{configStep}',
    configEnergySystem: '/energyeffect/configenergysystem/{customerId}/{hierarchyId}/{energyProblemId}/{energySystem}',
    updateEnergySystem: '/energyeffect/updateenergySystem/{customerId}/{hierarchyId}/{energyProblemId}/{energySystem}',
    addenergyeffecttag: '/energyeffect/addenergyeffecttag/{energyProblemId}/{tagId}',
    deleteenergyeffecttag: '/energyeffect/deleteenergyeffecttag/{energyProblemId}/{tagId}',
    getitem:'/energyeffect/getitem/{energyEffectItemId}',
    getcontrast:'/energyeffect/detail/contrast/{energyEffectId}/{energyEffectItemId}',
    getsaving:'/energyeffect/detail/saving/{energyEffectId}/{energyEffectItemId}',
    saveBest:'/energyeffect/bestsolution/save/{effectId}',
    deleteBest:'/energyeffect/bestsolution/delete/{effectId}',
    ignoreBest:'/energyeffect/bestsolution/ignore/{effectId}',
    getBest:'/energyeffect/bestsolution/list/{customerId}',
    groupOverviewCommodityShow:'/energyeffect/group/Overview/CommodityShow/{customerId}/{year}',
    buildingOverviewCommodityShow:'/energyeffect/building/Overview/CommodityShow/{hierarchyId}/{year}',
    groupOverviewTotal:'/energyeffect/group/Overview/total/{customerId}/{year}',
    buildingOverviewTotal:'/energyeffect/building/Overview/total/{hierarchyId}/{year}',
    BuildingShow:'/energyeffect/group/Overview/BuildingShow/{customerId}/{year}',
    overviewMinYear: '/energyeffect/Overview/MinYear/{isBuilding}/{hierarchyId}',
  },
  User:{
    startChangePassword:'/user/startChangePassword/{userName}'
  },
  Vee:{
    getAnomaly:'/vee/anomalyNotification/{nodeId}/{nodeType}/{anomalyType}'
  }
};
