language: node_js
sudo: required

services:
  - docker

node_js:
  - "6.10.2"

cache:
  yarn: true
  directories:
  - node_modules
  
env:
  global:
  - PROJECT="Jazz-UI"
  - ROLE="WebUI"
  - PACKAGE_VERSION="v4.6.0.${TRAVIS_BUILD_NUMBER}"
  - DOCKER_NS="se-rem-test"
  - secure: "h9vcatrcsxtm/4m/RaWdrh+GMbn34QLKfsqdgfJw+t3Jsi/zmliojeZGJSFDnFBzONpw4GF8aB2lfUvisogiyeshnKkRVfSY/21KVt7hN11SQSS0RtwPek9++6lbsNJ+6pNiePK+7mfCYQoZQDdWGvZwPu+1jmq/tDx4PTyFx+aGQi79fqbEnGgLcWZPKeFXYhSBJzuZC8l6xyPq3RJ4a+c99DsYIi9+qYPb7kY47ftdTZBMbTrBLWcP5kCN4e/raZ5XoLIzos8oim5+UVXkTxp13AnQekZqLZlPC8IK1zJF9pTuMOb7/MuEeZ22kLpthhI1bD5dxkHnO1wVTE+97wlgCPua8vnDeQAQ0R45ahi160PlNRU7TGV5RrnXqeabtkAeNMlK26m8ZKVkG9lsJULE1RV3Mfu/LhHh3pQtxtZidi4i6cDQGKos1TKWQ2gg3SWHpk0eUGcABttNwRySytxvTX5YRfjgt4cbsJWnK8ZnP8Ky0gq+LPF3dZQTyVLHNK6Icf1sdKQjkYfBmWVfuPgYlCwjiRwKEXXjEqH5PjKxIwvXvsPoe/RQvZPCDGN9buuLedK32t6/U760MLxPL3Lwn8FXLyyMzCZ+7YHq32olaayP0qvEWz3EIaZEVfDA2Gwuq0lb4GMsjxQifiB6canZ3Ryo5C5B5dhI5XFQkO0="

before_script:
  - export ARTIFACT_NAME="${PROJECT}-${ROLE}-${TRAVIS_BRANCH}-${PACKAGE_VERSION}.zip"
  - export TAG=`echo "$PROJECT-$ROLE:$TRAVIS_BRANCH-$PACKAGE_VERSION" | tr '[:upper:]' '[:lower:]'`
  - export TAG_LATEST=`echo "$PROJECT-$ROLE:$TRAVIS_BRANCH-latest" | tr '[:upper:]' '[:lower:]'`
  - export REMOTE_TAG=$DOCKER_REGISTRY/$DOCKER_NS/$TAG
  - export REMOTE_TAG_LATEST=$DOCKER_REGISTRY/$DOCKER_NS/$TAG_LATEST
  - export ARTIFACT_NAME="${PROJECT}-${ROLE}-${TRAVIS_BRANCH}-${PACKAGE_VERSION}.zip"
 
script:
#  - yarn run build-test
  - ls -la
  - docker build -t $TAG .
  - ls -la

before_deploy:
#  - cp compose-template.yml build/
#  - echo -n "${PACKAGE_VERSION}" > build/version.txt
#  - cd build && zip -r ../${ARTIFACT_NAME} ./ && cd ..
  - ls -la
  - echo -n "${PACKAGE_VERSION}" > version.txt
  - zip -r /tmp/${ARTIFACT_NAME} -x *node_modules* ./  
  - 'curl -o upload.sh -H "Authorization: token ${GITHUB_TOKEN}" ${GITHUB_UPLOAD_SCRIPT}'
  - chmod a+x ./upload.sh
  
  - IMAGEID=$(docker images $TAG -q)
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" $DOCKER_REGISTRY
  - docker tag $IMAGEID $REMOTE_TAG
  - docker tag $IMAGEID $REMOTE_TAG_LATEST
  - docker image ls
  - ls -la
  
deploy:
- provider: script
  skip_cleanup: true
  on:
    all_branches: true
  script:
#    - ./upload.sh /tmp/${ARTIFACT_NAME} ${PROJECT} ${TRAVIS_BRANCH} ${ROLE} ${PACKAGE_VERSION} ${OSS_BUCKET} ${OSS_KEY} ${OSS_SECRET} && curl -X POST "http://114.215.253.133:8081/job/Jazz/buildWithParameters?environment=dev&ui_version=latest&main_version=latest&branch=${TRAVIS_BRANCH}" --user ${JENKINS_AUTH} && docker push $REMOTE_TAG && docker push $REMOTE_TAG_LATEST
    - ./upload.sh /tmp/${ARTIFACT_NAME} ${PROJECT} ${TRAVIS_BRANCH} ${ROLE} ${PACKAGE_VERSION} ${OSS_BUCKET} ${OSS_KEY} ${OSS_SECRET} && docker push $REMOTE_TAG && docker push $REMOTE_TAG_LATEST
