{DOCKER:APP_NAME:WebUI}:
  restart: always
  image: '{DOCKER:IMAGE_FULL_NAME:WebUI}'
  ports:
    - 9083:80
  dns:
    - '10.160.23.21'
    - '10.47.144.11'
  dns_opt:
    - use-vc
    - no-tld-query
  dns_search:
    - hz.rem.cn.se.com
  environment:
    - NPM_CONFIG_LOGLEVEL=info
    - JAZZ_WEBAPI_HOST=${JAZZ_WEBAPI_HOST}
    - JAZZ_UI_UMENG_CNZZ_SDK_URL=${JAZZ_UI_UMENG_CNZZ_SDK_URL}
    - OSS_BUCKET=${UI_CDN_OSS_BUCKET}
    - OSS_REGION=${UI_CDN_OSS_REGION}
    - ALI_SDK_STS_ID=${COMMON_ALIYUN_ACCESS_ID}
    - ALI_SDK_STS_SECRET=${COMMON_ALIYUN_ACCESS_SECRET}
    - JAZZ_STATIC_CDN=${JAZZ_STATIC_CDN}
    - APP_VERSION=${JAZZ_UI_APP_VERSION}
    - APP_SIZE=${JAZZ_UI_APP_SIZE}
    - APP_DOWNLOAD_LOCAL=${JAZZ_UI_APP_DOWNLOAD_LOCAL}
    - APP_DOWNLOAD_QQ=${JAZZ_UI_APP_DOWNLOAD_QQ}
    - APP_DOWNLOAD_WDJ=${JAZZ_UI_APP_DOWNLOAD_WDJ}
    - APP_DOWNLOAD_BAIDU=${JAZZ_UI_APP_DOWNLOAD_BAIDU}
  memswap_limit: 0
  labels:
    aliyun.scale: '${JAZZ_UI_SCALE}'
    aliyun.lb.port_80: '${JAZZ_UI_LB}'
  shm_size: 
  memswap_reservation: 0
  kernel_memory: 0
  mem_limit: 0
