{DOCKER:APP_NAME:WebUI}:
  restart: always
  image: '{DOCKER:IMAGE_FULL_NAME:WebUI}'
  ports:
    - '80/tcp'
  dns:
    - '10.160.23.21'
    - '10.47.144.11'
  dns_opt:
    - use-vc
    - no-tld-query
  dns_search:
    - hz.rem.cn.se.com
  environment:
    - NPM_CONFIG_LOGLEVEL=info
    - JAZZ_WEBAPI_HOST=${JAZZ_WEBAPI_HOST}
    - JAZZ_UI_UMENG_CNZZ_SDK_URL=${JAZZ_UI_UMENG_CNZZ_SDK_URL}
  memswap_limit: 0
  labels:
    aliyun.scale: '1'
    aliyun.routing.port_80: '${JAZZ_WEB_HOST}'
  shm_size: 
  memswap_reservation: 0
  kernel_memory: 0
  mem_limit: 0
