import keyMirror from 'keymirror';

module.exports = {
  Action: keyMirror({
    GET_VEE_DATA_STRUCTURE_REQUEST: null,
    GET_VEE_DATA_STRUCTURE_SUCCESS: null,
    GET_VEE_DATA_STRUCTURE_FAILURE: null,
    GET_VEE_TAG_ANOMALY_SUCCESS:null,
    GET_VEE_SUMMARY_SUCCESS:null,
    GET_SCAN_SWITCH_REQUEST: null,
    GET_SCAN_SWITCH_SUCCESS: null,
    GET_VEE_TAG_ANOMALY_SUCCESS:null,
    UPDATE_READ_STATUS_SUCCESS:null,
    GET_RULE_BY_ID_SUCCESS:null,
    GET_TAG_SELECT_HIERARCHY_SUCCESS:null,
    GET_DATA_STRUCTURE_TAGS:null,
    GET_BASIC_PROPERTY_DATA: null,
    GET_BUILDING_BASIC_SUCCESS:null,
    GET_ALL_INDUSTRIES_FOR_DATAQUALITY:null,
    GET_ALL_ZONES_FOR_DATAQUALITY:null
  })
};
