import keyMirror from 'keymirror';

module.exports = {

  Action: keyMirror({
    GET_HIERARCHY_TREE_DTOS: null,
    SET_SELECTED_HIERARCHY_NODE: null,
    GET_CUSTOMER_FOR_HIERARCHY: null,
    GET_LOG_LIST_SUCCESS: null,
    GET_LOG_LIST_ERROR: null,
    DELETE_HIERARCHY_DTO_SUCCESS: null,
    HIERARCHY_ERROR: null,
    GET_ASSOCIATED_TAG: null,
    CLEAR_ALL_ASSOCIATED_TAGS: null,
    GET_CALENDAR_FOR_HIERARCHY: null,
    SET_CALENDAR_FOR_HIERARCHY: null,
    CANCEL_SAVE_CALENDAR: null,
    GET_PROPERTY_FOR_HIERARCHY: null,
    SET_PROPERTY_FOR_HIERARCHY: null,
    CANCEL_SAVE_PROPERTY: null,
    GET_ALL_CALENDARS_FOR_HIERARCHY: null,
    GET_ALL_INDUSTRIES_FOR_HIERARCHY: null,
    GET_ALL_ZONES_FOR_HIERARCHY: null,
    MODIFY_HIERARCHY_PATH: null,
    SET_ENERGY_CONSUMPTION: null,
    GET_COST_BY_HIERARCHY: null,
    SAVE_COST_BY_HIERARCHY_SUCCESS: null,
    RESET_ALL_FOR_HIERARCHY: null
  })

};
